import 'user_time_block.dart';
import 'enums.dart';

class TimeBlockTemplates {
  static List<UserTimeBlock> get defaultTemplates => [
    UserTimeBlock(
      name: 'Morning Golden Hours',
      startTime: '08:00',
      endTime: '11:00',
      daysOfWeek: [1, 2, 3, 4, 5], // Monday to Friday
      energyLevel: EnergyLevel.high,
      focusLevel: FocusLevel.deep,
      suitableCategories: [TaskCategory.creative, TaskCategory.analytical],
      suitablePriorities: [Priority.high],
      suitableEnergyLevels: [EnergyLevel.high, EnergyLevel.medium],
      description: 'High energy period, perfect for important and complex tasks',
      color: '#4CAF50',
      isDefault: true,
    ),
    UserTimeBlock(
      name: 'Late Morning Work',
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: [1, 2, 3, 4, 5],
      energyLevel: EnergyLevel.medium,
      focusLevel: FocusLevel.medium,
      suitableCategories: [TaskCategory.routine, TaskCategory.communication],
      suitablePriorities: [Priority.medium],
      suitableEnergyLevels: [EnergyLevel.medium, EnergyLevel.low],
      description: 'Before lunch, suitable for routine work',
      color: '#2196F3',
      isDefault: true,
    ),
    UserTimeBlock(
      name: 'Post-Lunch Recovery',
      startTime: '14:00',
      endTime: '15:30',
      daysOfWeek: [1, 2, 3, 4, 5],
      energyLevel: EnergyLevel.low,
      focusLevel: FocusLevel.light,
      suitableCategories: [TaskCategory.routine, TaskCategory.communication],
      suitablePriorities: [Priority.low, Priority.medium],
      suitableEnergyLevels: [EnergyLevel.low],
      description: 'Post-meal drowsiness, good for simple administrative tasks',
      color: '#FF9800',
      isDefault: true,
    ),
    UserTimeBlock(
      name: 'Afternoon Focus Time',
      startTime: '15:30',
      endTime: '17:30',
      daysOfWeek: [1, 2, 3, 4, 5],
      energyLevel: EnergyLevel.medium,
      focusLevel: FocusLevel.medium,
      suitableCategories: [TaskCategory.analytical, TaskCategory.communication],
      suitablePriorities: [Priority.medium, Priority.high],
      suitableEnergyLevels: [EnergyLevel.medium],
      description: 'Energy recovery, good for tasks requiring thinking',
      color: '#9C27B0',
      isDefault: true,
    ),
    UserTimeBlock(
      name: 'Evening Flex Time',
      startTime: '19:00',
      endTime: '21:00',
      daysOfWeek: [1, 2, 3, 4, 5],
      energyLevel: EnergyLevel.medium,
      focusLevel: FocusLevel.light,
      suitableCategories: [TaskCategory.creative, TaskCategory.routine],
      suitablePriorities: [Priority.low, Priority.medium],
      suitableEnergyLevels: [EnergyLevel.low, EnergyLevel.medium],
      description: 'Relaxed time for personal projects or learning',
      color: '#607D8B',
      isDefault: true,
    ),
  ];
}