import 'user_time_block.dart';
import 'enums.dart';

class TimeBlockTemplates {
  static List<UserTimeBlock> get defaultTemplates => [
    UserTimeBlock(
      name: '早晨黄金时间',
      startTime: '08:00',
      endTime: '11:00',
      daysOfWeek: [1, 2, 3, 4, 5], // 周一到周五
      energyLevel: EnergyLevel.high,
      focusLevel: FocusLevel.deep,
      suitableCategories: [TaskCategory.creative, TaskCategory.analytical],
      suitablePriorities: [Priority.high],
      suitableEnergyLevels: [EnergyLevel.high, EnergyLevel.medium],
      description: '精力充沛，适合处理重要且复杂的任务',
      color: '#4CAF50',
      isDefault: true,
    ),
    UserTimeBlock(
      name: '上午工作时间',
      startTime: '11:00',
      endTime: '12:00',
      daysOfWeek: [1, 2, 3, 4, 5],
      energyLevel: EnergyLevel.medium,
      focusLevel: FocusLevel.medium,
      suitableCategories: [TaskCategory.routine, TaskCategory.communication],
      suitablePriorities: [Priority.medium],
      suitableEnergyLevels: [EnergyLevel.medium, EnergyLevel.low],
      description: '临近午餐，适合处理常规工作',
      color: '#2196F3',
      isDefault: true,
    ),
    UserTimeBlock(
      name: '午后恢复期',
      startTime: '14:00',
      endTime: '15:30',
      daysOfWeek: [1, 2, 3, 4, 5],
      energyLevel: EnergyLevel.low,
      focusLevel: FocusLevel.light,
      suitableCategories: [TaskCategory.routine, TaskCategory.communication],
      suitablePriorities: [Priority.low, Priority.medium],
      suitableEnergyLevels: [EnergyLevel.low],
      description: '饭后困倦，适合处理简单事务性工作',
      color: '#FF9800',
      isDefault: true,
    ),
    UserTimeBlock(
      name: '下午高效期',
      startTime: '15:30',
      endTime: '17:30',
      daysOfWeek: [1, 2, 3, 4, 5],
      energyLevel: EnergyLevel.medium,
      focusLevel: FocusLevel.medium,
      suitableCategories: [TaskCategory.analytical, TaskCategory.communication],
      suitablePriorities: [Priority.medium, Priority.high],
      suitableEnergyLevels: [EnergyLevel.medium],
      description: '精力恢复，可以处理需要思考的任务',
      color: '#9C27B0',
      isDefault: true,
    ),
    UserTimeBlock(
      name: '晚间弹性时间',
      startTime: '19:00',
      endTime: '21:00',
      daysOfWeek: [1, 2, 3, 4, 5],
      energyLevel: EnergyLevel.medium,
      focusLevel: FocusLevel.light,
      suitableCategories: [TaskCategory.creative, TaskCategory.routine],
      suitablePriorities: [Priority.low, Priority.medium],
      suitableEnergyLevels: [EnergyLevel.low, EnergyLevel.medium],
      description: '相对轻松，可以处理个人项目或学习',
      color: '#607D8B',
      isDefault: true,
    ),
  ];
}